export const ADD_TODO = "ADD_TODO";
export const SET_TODO_COMPLETED = "SET_TODO_COMPLETED";
export const SET_ALL_COMPLETED = "SET_ALL_COMPLETED";
export const DELETE_ALL = "DELETE_ALL";
export const DELETE_TODO = "DELETE_TODO";